# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for Crypto News MCP Server
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml .
RUN pip install --no-cache-dir httpx mcp[cli] python-dotenv

# Copy project files
COPY . .

# Expose port if needed (FastMCP uses stdio by default)
# ENTRYPOINT
CMD ["python", "main.py"]
