# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir \
    "mcp[cli]>=1.7.0" \
    "websockets>=15.0.1"

# Copy project files
COPY . /app

# Expose standard streams
# Default command to run the MCP
CMD ["python", "main.py"]
