# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml .
RUN pip install --no-cache-dir mcp[cli]>=1.6.0 httpx>=0.28.1

# Copy application
COPY main.py .

# Expose no ports since MCP uses stdio

# Default command
CMD ["python", "main.py"]
