version: "3.8"

services:
    mcp-server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        volumes:
            - ./.env:/app/.env
        restart: unless-stopped
