# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Auto-generated Dockerfile for PancakeSwap PoolSpy MCP Server
FROM python:3.13-alpine

# Set work directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

# Copy project metadata
COPY pyproject.toml uv.lock ./

# Install Python dependencies
RUN pip install --no-cache-dir .

# Copy application source
COPY . .

# Default command to run the MCP server
CMD ["python3", "main.py"]
