[project]
name = "twitter-name-changes-mcp"
version = "0.1.0"
description = "An MCP server that tracks the historical changes of Twitter usernames."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
