name: demcp_defillama_mcp
description: "Defillama MCP"
version: 1.0.0
model: sse
env:
mcp_config:
  tools:
    - name: get_protocols
      description: "Get all protocols from defillama"
    - name: get_protocol_tvl
      description: "Get the tvl of a protocol from defillama"
    - name: get_chain_tvl
      description: "Get the tvl of a chain from defillama"
    - name: get_token_prices
      description: "Get the price of a token from defillama"
    - name: get_pools
      description: "Get all pools from defillama"
    - name: get_pool_tvl
      description: "Get the tvl of a pool from defillama"
start_config:
  command: "python"
  args:
    - "defillama.py"
    - "--allow-env"
    - "--allow-net"
    - "--allow-read"
    - "jsr:@demcp/defillama-mcp"