# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create and set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the project
RUN npm run build

# Optionally expose a port if needed (the settings.json indicates port 3000, but the server communicates over stdio)
# EXPOSE 3000

# Start the MCP server
CMD [ "npm", "start" ]
